### ISSUE TITLE
Credit Original Project

### ISSUE THREAD

**Issue by John-Leitch** [nimrods8/ntlmv2-cracker#1]
I'm happy to see somebody building something new based on a fork of my work, but could you link to the original project and give me proper credit? The project of mine you forked is located here: https://github.com/John-Leitch/fpga-md5-cracker

Also, you may like to know I first released MD5 module on opencores under the LGPL license: https://opencores.org/websvn,filedetails?repname=md5_pipelined&path=%2Fmd5_pipelined%2Ftrunk%2FMd5Core.v

I'm not particularly concerned, but it's best to be aware of such things.

**Comment by nimrods8** [comment]
Proper credit to John Leitch's project added
